runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  APP_HOST: 0.0.0.0
  APP_PORT: $PORT
  SECRET_KEY: [YOUR_SECRET_KEY]
  CLIENT_ID: [YOUR_CLIENT_ID]
  CLIENT_SECRET: [YOUR_CLIENT_SECRET]
  DOMAIN: [YOUR_DOMAIN_IN_AUTH0]
  BUCKET_NAME: [YOUR_BUCKET_NAME_IN_GOOGLE_CLOUD_STORAGE]
  GOOGLE_APPLICATION_CREDENTIALS: [YOUR_CREDENTIALS_FILE_IN_GOOGLE_CLOUD_STORAGE]
  APP_URL: https://[project_ID].[region_id].r.appspot.com